name = "cookie-share"
main = "_worker.js"
compatibility_date = "2024-03-18"
account_id = "" # 请用户替换成他们的 Cloudflare Account ID

# Environment variables
[vars]
ADMIN_PASSWORD = "WrC9baV^QuvovwP7YDha" # 用户部署时在 Cloudflare UI 中设置
PATH_SECRET = "WrC9baV^QuvovwP7YDhahdrhdhdhhbv67547"    # 用户部署时在 Cloudflare UI 中设置

# KV namespace binding
kv_namespaces = [
  { binding = "COOKIE_STORE", preview_id="", id = "" } # 用户部署时在 Cloudflare UI 中创建和绑定
] 